name: Build & Deploy (GitHub Pages)

on:
  push: {}
  pull_request: {}
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ./dist
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Install Git LFS and fetch LFS objects
        run: |
          if ! command -v git-lfs >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y git-lfs
          fi
          git lfs install --local
          # try to pull only files under `public/` (faster); fall back to pulling all if that fails
          git lfs pull --include="public/**" || git lfs pull --all

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build site
        run: npm run build

      - name: Upload Pages artifact
        id: upload-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
